### ISSUE TITLE
Add development documentation

### ISSUE THREAD

**Issue by ptaranat** [Ashmogh/morii-vtt#125]
We may want to include details on spinning up a local dev environment.

- Set up MongoDB docker container
- Set up `.env` file
- Command to run `MONGO_URL=mongodb://localhost:27017 MONGO_INITDB_DATABASE=morii-db yarn run-stack-dev`

**Comment by Ashmogh** [comment]
I've added dev environment documentation to README in 0ed80df, though if there is any improvement to be made, let me know.
