### ISSUE TITLE
Import Cairn character sheet from JSON

### ISSUE THREAD

**Issue by ptaranat** [Ashmogh/morii-vtt#82]
## Feature Request

Currently, we can export Cairn characters to JSON, but we cannot import them when creating a new character or NPC, only copying existing sheets. The functionality exists in 5e.

**Comment by Ashmogh** [comment]
Importing JSONs is tricky as we don't really want to let the user to just import whichever json file they want. For both 5E and the roll20 import I've added JSON schemas as well as their respective validators to `main.ts` and we would probably need those for other systems as well.

**Comment by ptaranat** [comment]
Let's use the JSON schema for the Cairn Foundry VTT plugin https://github.com/yochaigal/Cairn-FoundryVTT/blob/master/template.json
