### ISSUE TITLE
Relics and items with charges

### ISSUE THREAD

**Issue by ptaranat** [Ashmogh/morii-vtt#92]
Relics are like spell books except they do not cause Fatigue. We should add functionality that supports Relics by allowing users to create items that hold charges.

We can represent charges with [circle outlines](https://icon-sets.iconify.design/mdi/checkbox-blank-circle-outline/), and used up charges with [filled circles](https://icon-sets.iconify.design/mdi/checkbox-blank-circle/) or [crossed out circles](https://icon-sets.iconify.design/mdi/circle-off-outline/). Crossed-out is less ambiguous. This iconography is similar to [Mausritter](https://mausritter.com/item-card-studio/) which Cairn is directly inspired by.

We can represent the charge functionality with lightning bolts.

**Comment by Ashmogh** [comment]
Relics would be a great addition! We could probably add them as a new item type `'relic'`, and the `mdi:lightning-bolt` icon. Not sure if filled or crossed out circle is better for charge keeping, would have to see both variants. 

I would see the 'where' we put charges circles as a bit more problematic, if we only add the charges keeping e.g. to the left of the `stacks/bulky` icons, the names of relics would be centred bit to left in contrast with other item types. One solution would be to add dynamic `grid-template-areas` and add simple empty cell to the right of the item type icon for only the relic type. This would limit the space for item name, however.

We might need to solve #91 first for relics to work, as we don't currently have a way for items to have no weight.

**Comment by ptaranat** [comment]
I believe Relics do take up space in the inventory as they are kinda like spell books. But agree that 91 is a higher priority.

**Comment by Ashmogh** [comment]
You are right! I confused them with scrolls, as both do not cause fatigue, but relics do take up space and scrolls do not.
