### ISSUE TITLE
Let players create NPCs

### ISSUE THREAD

**Issue by ptaranat** [Ashmogh/morii-vtt#93]
PCs can hire hirelings. Some optional gear packages come with animal companions that behave like hirelings. We should allow the creation and management of NPCs for players using same or similar interface for GMs.

Otherwise, we could let GMs control NPCs entirely. This may be the best option for now.

**Comment by Ashmogh** [comment]
For now I would let only GM control NPCs as it is currently tied too tightly within the `Game` view as a whole. NPCs were originally only meant as GMs equivalent to players' characters.

We could in the future potentially add a separate simplifed view for something like hirelings (maybe similar to how `Monsters` work in 5E but accessible to everyone).

**Comment by ptaranat** [comment]
Closed in favor of letting GMs control NPCs. Possible planned feature for hirelings.
